/* tslint:disable */
/* eslint-disable */
/**
 * Takeda API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @enum {string}
 */
export enum ErrorCode {
    UserNotFound = 0,
    EmailInUse = 1,
    IdPresentInCreate = 2,
    InvalidEmailOrPassword = 3,
    ActionForbidden = 4,
    NotFound = 5,
    PropertyNotFound = 6,
    CantReauthenticate = 7,
    PhoneNumberNotVerified = 8,
    PhoneNumberAlreadyVerified = 9,
    PhoneNumberAlreadyInUse = 10,
    PhoneNumberFormatInvalid = 11,
    InvalidOrExpiredCode = 12,
    PasswordConfirmationNotSame = 13,
    SyncRequestAlreadyExists = 14,
    AlertNotFound = 15,
    EmailNotVerified = 16,
    PromotionNotFound = 17,
    GeofenceNotFound = 18,
    CodeResendTimeout = 19,
    ChatNotFound = 20,
    PromotionsNotFound = 21,
    BrandImageNotFound = 22,
    BrandImageIsActive = 23,
    UserNotVerified = 24,
    ValidationErrors = 10000,
    Required = 10001,
    NotValidEmailAddress = 10002,
    MinLength = 10003,
    MaxLength = 10004,
    Length = 10005,
    GreaterThanOrEqual = 10006,
    GreaterThan = 10007,
    LessThanOrEqual = 10008,
    LessThan = 10009,
    NotEqual = 10010,
    Predicate = 10011,
    Regex = 10012,
    Equal = 10013,
    ExactLength = 10014,
    Between = 10015,
    Empty = 10016,
    Invalid = 10017
}

/**
 * 
 * @export
 * @interface ErrorResponseDto
 */
export interface ErrorResponseDto {
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseDto
     */
    detail?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseDto
     */
    title?: string | null;
    /**
     * 
     * @type {HttpStatusCode}
     * @memberof ErrorResponseDto
     */
    status?: HttpStatusCode;
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseDto
     */
    type?: string | null;
    /**
     * 
     * @type {Array<ValidationFieldErrorDto>}
     * @memberof ErrorResponseDto
     */
    errors?: Array<ValidationFieldErrorDto> | null;
}
/**
 * 
 * @export
 * @interface FileResponseDto
 */
export interface FileResponseDto {
    /**
     * 
     * @type {number}
     * @memberof FileResponseDto
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof FileResponseDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FileResponseDto
     */
    url?: string | null;
    /**
     * 
     * @type {number}
     * @memberof FileResponseDto
     */
    newsId?: number | null;
    /**
     * 
     * @type {FileType}
     * @memberof FileResponseDto
     */
    type?: FileType;
}
/**
 * 
 * @export
 * @enum {string}
 */
export enum FileType {
    Full = 0,
    Preview = 1
}

/**
 * 
 * @export
 * @enum {string}
 */
export enum HttpStatusCode {
    Continue = 100,
    SwitchingProtocols = 101,
    Processing = 102,
    EarlyHints = 103,
    OK = 200,
    Created = 201,
    Accepted = 202,
    NonAuthoritativeInformation = 203,
    NoContent = 204,
    ResetContent = 205,
    PartialContent = 206,
    MultiStatus = 207,
    AlreadyReported = 208,
    IMUsed = 226,
    MultipleChoices = 300,
    Ambiguous = 301,
    MovedPermanently = 302,
    Moved = 303,
    Found = 304,
    Redirect = 305,
    SeeOther = 306,
    RedirectMethod = 307,
    NotModified = 308,
    UseProxy = 400,
    Unused = 401,
    TemporaryRedirect = 402,
    RedirectKeepVerb = 403,
    PermanentRedirect = 404,
    BadRequest = 405,
    Unauthorized = 406,
    PaymentRequired = 407,
    Forbidden = 408,
    NotFound = 409,
    MethodNotAllowed = 410,
    NotAcceptable = 411,
    ProxyAuthenticationRequired = 412,
    RequestTimeout = 413,
    Conflict = 414,
    Gone = 415,
    LengthRequired = 416,
    PreconditionFailed = 417,
    RequestEntityTooLarge = 421,
    RequestUriTooLong = 422,
    UnsupportedMediaType = 423,
    RequestedRangeNotSatisfiable = 424,
    ExpectationFailed = 426,
    MisdirectedRequest = 428,
    UnprocessableEntity = 429,
    Locked = 431,
    FailedDependency = 451,
    UpgradeRequired = 500,
    PreconditionRequired = 501,
    TooManyRequests = 502,
    RequestHeaderFieldsTooLarge = 503,
    UnavailableForLegalReasons = 504,
    InternalServerError = 505,
    NotImplemented = 506,
    BadGateway = 507,
    ServiceUnavailable = 508,
    GatewayTimeout = 510,
    HttpVersionNotSupported = 511
}

/**
 * 
 * @export
 * @interface LoginRequestDto
 */
export interface LoginRequestDto {
    /**
     * 
     * @type {string}
     * @memberof LoginRequestDto
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LoginRequestDto
     */
    password?: string | null;
}
/**
 * 
 * @export
 * @interface RefreshTokenRequestDto
 */
export interface RefreshTokenRequestDto {
    /**
     * 
     * @type {string}
     * @memberof RefreshTokenRequestDto
     */
    accessToken?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RefreshTokenRequestDto
     */
    refreshToken?: string | null;

    /**
     * 
     * @type {number}
     * @memberof RefreshTokenRequestDto
     */
    userId?: number | null;
}
/**
 * 
 * @export
 * @interface TimeSpan
 */
export interface TimeSpan {
    /**
     * 
     * @type {number}
     * @memberof TimeSpan
     */
    ticks?: number;
    /**
     * 
     * @type {number}
     * @memberof TimeSpan
     */
    days?: number;
    /**
     * 
     * @type {number}
     * @memberof TimeSpan
     */
    hours?: number;
    /**
     * 
     * @type {number}
     * @memberof TimeSpan
     */
    milliseconds?: number;
    /**
     * 
     * @type {number}
     * @memberof TimeSpan
     */
    minutes?: number;
    /**
     * 
     * @type {number}
     * @memberof TimeSpan
     */
    seconds?: number;
    /**
     * 
     * @type {number}
     * @memberof TimeSpan
     */
    totalDays?: number;
    /**
     * 
     * @type {number}
     * @memberof TimeSpan
     */
    totalHours?: number;
    /**
     * 
     * @type {number}
     * @memberof TimeSpan
     */
    totalMilliseconds?: number;
    /**
     * 
     * @type {number}
     * @memberof TimeSpan
     */
    totalMinutes?: number;
    /**
     * 
     * @type {number}
     * @memberof TimeSpan
     */
    totalSeconds?: number;
}
/**
 * 
 * @export
 * @interface TokenResponseDto
 */
export interface TokenResponseDto {
    /**
     * 
     * @type {string}
     * @memberof TokenResponseDto
     */
    accessToken?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TokenResponseDto
     */
    refreshToken?: string | null;
}

/**
 * 
 * @export
 * @interface ChangePasswordRequestDto
 */
export interface ChangePasswordRequestDto {
    /**
     * 
     * @type {string}
     * @memberof ChangePasswordRequestDto
     */
    password?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChangePasswordRequestDto
     */
    passwordConfirmation?: string | null;
}
/**
 * 
 * @export
 * @interface UserResponseDto
 */
export interface UserResponseDto {
    /**
     * 
     * @type {number}
     * @memberof UserResponseDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof UserResponseDto
     */
    name?: string | null;
     /**
     * 
     * @type {string}
     * @memberof UserResponseDto
     */
    username?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserResponseDto
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserResponseDto
     */
    senderName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserResponseDto
     */
    email?: string | null;
    /**
     * 
     * @type {UserRoleEnum}
     * @memberof UserResponseDto
     */
    role?: UserRoleEnum;
    /**
     * 
     * @type {UserStatusEnum}
     * @memberof UserResponseDto
     */
    status?: UserStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof UserResponseDto
     */
    createdOn?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserResponseDto
     */
    updatedOn?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserResponseDto
     */
    emailVerifiedAt?: string | null;
}
/**
 * 
 * @export
 * @interface UserResponseDtoPagedResponse
 */
export interface UserResponseDtoPagedResponse {
    /**
     * 
     * @type {Array<UserResponseDto>}
     * @memberof UserResponseDtoPagedResponse
     */
    results?: Array<UserResponseDto> | null;
    /**
     * 
     * @type {number}
     * @memberof UserResponseDtoPagedResponse
     */
    totalResults?: number;
    /**
     * 
     * @type {number}
     * @memberof UserResponseDtoPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof UserResponseDtoPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof UserResponseDtoPagedResponse
     */
    totalPages?: number;
}
/**
 * 
 * @export
 * @enum {string}
 */
export enum UserRoleEnum {
    Superadmin = 1,
    Admin = 2,
}

export enum UserStatusEnum {
    Active = 1,
    Inactive = 2
}

/**
 * 
 * @export
 * @interface ForgotPasswordRequestDto
 */
export interface ForgotPasswordRequestDto {
    /**
     * 
     * @type {string}
     * @memberof ForgotPasswordRequestDto
     */
    email?: string | null;
}

/**
 * 
 * @export
 * @interface ValidationFieldErrorDto
 */
export interface ValidationFieldErrorDto {
    // /**
    //  * 
    //  * @type {string}
    //  * @memberof ValidationFieldErrorDto
    //  */
    // field?: string | null;
    // /**
    //  * 
    //  * @type {string}
    //  * @memberof ValidationFieldErrorDto
    //  */
    // error?: string | null;
    // /**
    //  * 
    //  * @type {any}
    //  * @memberof ValidationFieldErrorDto
    //  */
    // extra?: any | null;
    code: string | null;
    message: Object | null;
}

/**
 * Request parameters for apiUsersForgotPasswordRequestPost operation in UsersApi.
 * @export
 * @interface UsersApiApiUsersForgotPasswordRequestPostRequest
 */
export interface UsersApiApiUsersForgotPasswordRequestPostRequest {
    /**
     * 
     * @type {ForgotPasswordRequestDto}
     * @memberof UsersApiApiUsersForgotPasswordRequestPost
     */
    readonly forgotPasswordRequestDto?: ForgotPasswordRequestDto
}

/**
 * 
 * @export
 * @interface UpdateMePasswordRequestDto
 */
export interface UpdateMePasswordRequestDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateMePasswordRequestDto
     */
    password?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateMePasswordRequestDto
     */
    passwordConfirmation?: string | null;
}

/**
 * 
 * @export
 * @interface ForgotPasswordVerifyCodeDto
 */
export interface ForgotPasswordVerifyCodeDto {
    /**
     * 
     * @type {string}
     * @memberof ForgotPasswordVerifyCodeDto
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ForgotPasswordVerifyCodeDto
     */
    code?: string | null;
}

/**
 * 
 * @export
 * @interface ResendVerificationEmailDto
 */
export interface ResendVerificationEmailDto {
    /**
     * 
     * @type {string}
     * @memberof ResendVerificationEmailDto
     */
    id?: number | null;
}

/**
 * 
 * @export
 * @interface VerifyEmailDto
 */
export interface VerifyEmailDto {
    /**
     * 
     * @type {string}
     * @memberof VerifyEmailDto
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof VerifyEmailDto
     */
    code?: string | null;
}

/**
 * 
 * @export
 * @interface ForgotPasswordResetDto
 */
export interface ForgotPasswordResetDto {
    /**
     * 
     * @type {string}
     * @memberof ForgotPasswordResetDto
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ForgotPasswordResetDto
     */
    code?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ForgotPasswordResetDto
     */
    password?: string | null;
}


/**
 * Request parameters for loginPost operation in TokensApi.
 * @export
 * @interface TokensApiLoginPostRequest
 */
export interface TokensApiLoginPostRequest {
    /**
     * 
     * @type {LoginRequestDto}
     * @memberof TokensApiLoginPost
     */
    readonly loginRequestDto?: LoginRequestDto
}

/**
 * Request parameters for refreshTokenPost operation in TokensApi.
 * @export
 * @interface TokensApiRefreshTokenPostRequest
 */
export interface TokensApiRefreshTokenPostRequest {
    /**
     * 
     * @type {RefreshTokenRequestDto}
     * @memberof TokensApiRefreshTokenPost
     */
    readonly refreshTokenRequestDto?: RefreshTokenRequestDto
}


/**
 * Request parameters for apiAdminUsersGet operation in AdminUsersApi.
 * @export
 * @interface AdminUsersApiApiAdminUsersGetRequest
 */
export interface AdminUsersApiApiAdminUsersGetRequest {
    /**
     * 
     * @type {string}
     * @memberof AdminUsersApiApiAdminUsersGet
     */
    readonly includes?: string

    /**
     * 
     * @type {number}
     * @memberof AdminUsersApiApiAdminUsersGet
     */
    readonly pageSize?: number

    /**
     * 
     * @type {number}
     * @memberof AdminUsersApiApiAdminUsersGet
     */
    readonly page?: number

    /**
     * 
     * @type {number}
     * @memberof AdminUsersApiApiAdminUsersGet
     */
    readonly fromId?: number

    /**
     * 
     * @type {string}
     * @memberof AdminUsersApiApiAdminUsersGet
     */
    readonly updatedAfter?: string

    /**
     * 
     * @type {string}
     * @memberof AdminUsersApiApiAdminUsersGet
     */
    readonly orderByKey?: string

    /**
     * 
     * @type {boolean}
     * @memberof AdminUsersApiApiAdminUsersGet
     */
    readonly isDescending?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof AdminUsersApiApiAdminUsersGet
     */
    readonly isFullSize?: boolean

    /**
     * 
     * @type {string}
     * @memberof AdminUsersApiApiAdminUsersGet
     */
    readonly query?: string

    /**
     * 
     * @type {string}
     * @memberof AdminUsersApiApiAdminUsersGet
     */
    readonly filter?: string
}

/**
 * Request parameters for apiAdminUsersIdDelete operation in AdminUsersApi.
 * @export
 * @interface AdminUsersApiApiAdminUsersIdDeleteRequest
 */
export interface AdminUsersApiApiAdminUsersIdDeleteRequest {
    /**
     * 
     * @type {number}
     * @memberof AdminUsersApiApiAdminUsersIdDelete
     */
    readonly id: number
}

/**
 * Request parameters for apiAdminUsersIdGet operation in AdminUsersApi.
 * @export
 * @interface AdminUsersApiApiAdminUsersIdGetRequest
 */
export interface AdminUsersApiApiAdminUsersIdGetRequest {
    /**
     * 
     * @type {number}
     * @memberof AdminUsersApiApiAdminUsersIdGet
     */
    readonly id: number
}

/**
 * Request parameters for apiAdminUsersIdRejectPost operation in AdminUsersApi.
 * @export
 * @interface AdminUsersApiApiAdminUsersIdRejectPostRequest
 */
export interface AdminUsersApiApiAdminUsersIdRejectPostRequest {
    /**
     * 
     * @type {number}
     * @memberof AdminUsersApiApiAdminUsersIdRejectPost
     */
    readonly id: number
}

/**
 * Request parameters for apiAdminUsersNewAdminPost operation in AdminUsersApi.
 * @export
 * @interface AdminUsersApiApiAdminUsersNewAdminPostRequest
 */
export interface AdminUsersApiApiAdminUsersNewAdminPostRequest {
    /**
     * 
     * @type {number}
     * @memberof AdminUsersApiApiAdminUsersNewAdminPost
     */
    readonly id?: number

    /**
     * 
     * @type {string}
     * @memberof AdminUsersApiApiAdminUsersNewAdminPost
     */
    readonly name?: string

    /**
     * 
     * @type {string}
     * @memberof AdminUsersApiApiAdminUsersNewAdminPost
     */
    readonly username?: string

    /**
     * 
     * @type {string}
     * @memberof AdminUsersApiApiAdminUsersNewAdminPost
     */
    readonly phoneNumber?: string

    /**
     * 
     * @type {string}
     * @memberof AdminUsersApiApiAdminUsersNewAdminPost
     */
    readonly phoneRegion?: string

    /**
     * 
     * @type {string}
     * @memberof AdminUsersApiApiAdminUsersNewAdminPost
     */
    readonly senderName?: string

    /**
     * 
     * @type {string}
     * @memberof AdminUsersApiApiAdminUsersNewAdminPost
     */
    readonly email?: string

    /**
     * 
     * @type {string}
     * @memberof AdminUsersApiApiAdminUsersNewAdminPost
     */
    readonly password?: string

    /**
     * 
     * @type {string}
     * @memberof AdminUsersApiApiAdminUsersNewAdminPost
     */
    readonly passwordConfirm?: string

    /**
     * 
     * @type {UserRoleEnum}
     * @memberof AdminUsersApiApiAdminUsersNewAdminPost
     */
    readonly role?: UserRoleEnum,

    /**
     * 
     * @type {UserStatusEnum}
     * @memberof AdminUsersApiApiAdminUsersNewAdminPost
     */
    readonly status?: UserStatusEnum
}

/**
 * Request parameters for apiAdminUsersPost operation in AdminUsersApi.
 * @export
 * @interface AdminUsersApiApiAdminUsersPostRequest
 */
export interface AdminUsersApiApiAdminUsersPostRequest {
    /**
     * 
     * @type {number}
     * @memberof AdminUsersApiApiAdminUsersPost
     */
    readonly id?: number

    /**
     * 
     * @type {string}
     * @memberof AdminUsersApiApiAdminUsersPost
     */
    readonly name?: string

    /**
     * 
     * @type {string}
     * @memberof AdminUsersApiApiAdminUsersPost
     */
    readonly phoneNumber?: string

    /**
     * 
     * @type {string}
     * @memberof AdminUsersApiApiAdminUsersPost
     */
    readonly specialisation?: string

    /**
     * 
     * @type {string}
     * @memberof AdminUsersApiApiAdminUsersPost
     */
    readonly title?: string

    /**
     * 
     * @type {string}
     * @memberof AdminUsersApiApiAdminUsersPost
     */
    readonly email?: string

    /**
     * 
     * @type {boolean}
     * @memberof AdminUsersApiApiAdminUsersPost
     */
    readonly approved?: boolean

    /**
     * 
     * @type {UserRoleEnum}
     * @memberof AdminUsersApiApiAdminUsersPost
     */
    readonly role?: UserRoleEnum

    /**
     * 
     * @type {string}
     * @memberof AdminUsersApiApiAdminUsersPost
     */
    readonly password?: string

    /**
     * 
     * @type {any}
     * @memberof AdminUsersApiApiAdminUsersPost
     */
    readonly profileImage?: any

    /**
     * 
     * @type {string}
     * @memberof AdminUsersApiApiAdminUsersPost
     */
    readonly categories?: string

    /**
     * 
     * @type {boolean}
     * @memberof AdminUsersApiApiAdminUsersPost
     */
    readonly adminAccessMedCenter?: boolean
}

/**
 * Request parameters for apiAdminUsersPut operation in AdminUsersApi.
 * @export
 * @interface AdminUsersApiApiAdminUsersPutRequest
 */
export interface AdminUsersApiApiAdminUsersPutRequest {
    /**
     * 
     * @type {number}
     * @memberof AdminUsersApiApiAdminUsersPut
     */
    readonly id?: number

    /**
     * 
     * @type {string}
     * @memberof AdminUsersApiApiAdminUsersPut
     */
    readonly name?: string

    /**
     * 
     * @type {string}
     * @memberof AdminUsersApiApiAdminUsersPut
     */
    readonly username?: string

    /**
     * 
     * @type {string}
     * @memberof AdminUsersApiApiAdminUsersPut
     */
    readonly phoneNumber?: string

    /**
     * 
     * @type {string}
     * @memberof AdminUsersApiApiAdminUsersPut
     */
    readonly phoneRegion?: string

    /**
     * 
     * @type {string}
     * @memberof AdminUsersApiApiAdminUsersPut
     */
    readonly senderName?: string

    /**
     * 
     * @type {string}
     * @memberof AdminUsersApiApiAdminUsersPut
     */
    readonly email?: string

    /**
     * 
     * @type {UserRoleEnum}
     * @memberof AdminUsersApiApiAdminUsersPut
     */
    readonly role?: UserRoleEnum

    /**
     * 
     * @type {string}
     * @memberof AdminUsersApiApiAdminUsersPut
     */
    readonly password?: string

    /**
     * 
     * @type {string}
     * @memberof AdminUsersApiApiAdminUsersPut
     */
    readonly passwordConfirm?: string

    /**
     * 
     * @type {UserStatusEnum}
     * @memberof AdminUsersApiApiAdminUsersPut
     */
    readonly status?: UserStatusEnum
}


/**
 * Request parameters for registerPost operation in TokensApi.
 * @export
 * @interface TokensApiRegisterPostRequest
 */
export interface TokensApiRegisterPostRequest {
    /**
     * 
     * @type {string}
     * @memberof TokensApiRegisterPost
     */
    readonly email?: string

    /**
     * 
     * @type {string}
     * @memberof TokensApiRegisterPost
     */
    readonly name?: string

    /**
     * 
     * @type {string}
     * @memberof TokensApiRegisterPost
     */
    readonly phoneNumber?: string

    /**
     * 
     * @type {string}
     * @memberof TokensApiRegisterPost
     */
    readonly specialisation?: string

    /**
     * 
     * @type {string}
     * @memberof TokensApiRegisterPost
     */
    readonly title?: string

    /**
     * 
     * @type {string}
     * @memberof TokensApiRegisterPost
     */
    readonly password?: string

    /**
     * 
     * @type {string}
     * @memberof TokensApiRegisterPost
     */
    readonly fcmToken?: string

    /**
     * 
     * @type {UserRoleEnum}
     * @memberof TokensApiRegisterPost
     */
    readonly role?: UserRoleEnum

    /**
     * 
     * @type {any}
     * @memberof TokensApiRegisterPost
     */
    readonly profileImage?: any
}

/**
 * Request parameters for apiUsersForgotPasswordResetPasswordPost operation in UsersApi.
 * @export
 * @interface UsersApiApiUsersForgotPasswordResetPasswordPostRequest
 */
export interface ApiUsersVerifyEmailPostRequest {
    /**
     * 
     * @type {VerifyEmailDto}
     * @memberof ApiUsersVerifyEmailPostRequest
     */
    readonly verifyEmailDto?: VerifyEmailDto
}

/**
 * Request parameters for apiUsersForgotPasswordResetPasswordPost operation in UsersApi.
 * @export
 * @interface UsersApiApiUsersForgotPasswordResetPasswordPostRequest
 */
export interface ApiUsersResendVerificationEmailPostRequest {
    /**
     * 
     * @type {ResendVerificationEmailDto}
     * @memberof ApiUsersResendVerificationEmailPostRequest
     */
    readonly resendVerificationEmailDto?: ResendVerificationEmailDto
}

/**
 * Request parameters for apiUsersForgotPasswordResetPasswordPost operation in UsersApi.
 * @export
 * @interface UsersApiApiUsersForgotPasswordResetPasswordPostRequest
 */
export interface UsersApiApiUsersForgotPasswordResetPasswordPostRequest {
    /**
     * 
     * @type {ForgotPasswordResetDto}
     * @memberof UsersApiApiUsersForgotPasswordResetPasswordPost
     */
    readonly forgotPasswordResetDto?: ForgotPasswordResetDto
}

/**
 * Request parameters for apiUsersForgotPasswordVerifyCodePost operation in UsersApi.
 * @export
 * @interface UsersApiApiUsersForgotPasswordVerifyCodePostRequest
 */
export interface UsersApiApiUsersForgotPasswordVerifyCodePostRequest {
    /**
     * 
     * @type {ForgotPasswordVerifyCodeDto}
     * @memberof UsersApiApiUsersForgotPasswordVerifyCodePost
     */
    readonly forgotPasswordVerifyCodeDto?: ForgotPasswordVerifyCodeDto
}

/**
 * Request parameters for apiUsersIdGet operation in UsersApi.
 * @export
 * @interface UsersApiApiUsersIdGetRequest
 */
export interface UsersApiApiUsersIdGetRequest {
    /**
     * 
     * @type {number}
     * @memberof UsersApiApiUsersIdGet
     */
    readonly id: number
}

/**
 * Request parameters for apiUsersMeChangePasswordPut operation in UsersApi.
 * @export
 * @interface UsersApiApiUsersMeChangePasswordPutRequest
 */
export interface UsersApiApiUsersMeChangePasswordPutRequest {
    /**
     * 
     * @type {ChangePasswordRequestDto}
     * @memberof UsersApiApiUsersMeChangePasswordPut
     */
    readonly ChangePasswordRequestDto?: ChangePasswordRequestDto
}

/**
 * Request parameters for apiUsersMePut operation in UsersApi.
 * @export
 * @interface UsersApiApiUsersMePutRequest
 */
export interface UsersApiApiUsersMePutRequest {
    /**
     * 
     * @type {number}
     * @memberof UsersApiApiUsersMePut
     */
    readonly id?: number

    /**
     * 
     * @type {string}
     * @memberof UsersApiApiUsersMePut
     */
    readonly name?: string

    /**
     * 
     * @type {string}
     * @memberof UsersApiApiUsersMePut
     */
    readonly password?: string

    /**
     * 
     * @type {string}
     * @memberof UsersApiApiUsersMePut
     */
    readonly email?: string
}

/**
 * 
 * @export
 * @interface UserResponseDtoPagedResponse
 */
export interface UserResponseDtoPagedResponse {
    /**
     * 
     * @type {Array<UserResponseDto>}
     * @memberof UserResponseDtoPagedResponse
     */
    results?: Array<UserResponseDto> | null;
    /**
     * 
     * @type {number}
     * @memberof UserResponseDtoPagedResponse
     */
    totalResults?: number;
    /**
     * 
     * @type {number}
     * @memberof UserResponseDtoPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof UserResponseDtoPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof UserResponseDtoPagedResponse
     */
    totalPages?: number;
}